# Change PORT_REDIRECT to match the actual redirectin ports 
ip_server=127.0.0.1
ip_redirect=127.0.0.1
chance_type=COUNT # Or %
chance_value=100  # Either after X connection or with a X% chance
target=*
max_socket_connections=5

# You can use as much of these as you want
# When the proxy reads a packet on PROXY_PORT, it redirects to IP_REDIRECT:SERVER_PORT
# bind PROXY_PORT WEBSITE_PORT
bind 8000 80
